version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/usr/src/app