version: '3'

services:
  backend:
    container_name: tacs_backend
    image: docker.pkg.github.com/paniaton/tacs2020/tacs-backend:0.0.2
    ports:
      - "8080:8080"
    environment:
      - dbUrl=mongodb
      
  telegram-bot:
    container_name: tacs-telegrambot
    image: docker.pkg.github.com/paniaton/tacs2020/tacs-telegrambot:0.0.4
    ports:
      - "8082:8082"

  mongodb_container:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: