version: '3'

services:
  backend:
    container_name: tacs_backend
    image: docker.pkg.github.com/paniaton/tacs2020/tacs-backend:0.0.1
    ports:
      - "8080:8080"
    environment:
      - dbUrl=mongodb

  frontend:
    container_name: tacs-frontend
    image: docker.pkg.github.com/paniaton/tacs2020/tacs-frontend:0.0.1
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/usr/src/app

  telegram-bot:
    build: ./telegramBot
    ports:
      - "8082:8082"

  mongodb_container:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: