version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
      
  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/usr/src/app
      
  mongodb_container:
    container_name: mongoDB
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: