package com.utn.tacs.utils

val countriesNamesMap = mapOf<String,String>(
    "AF" to "Afghanistan",
    "AL" to "Albania",
    "DZ" to "Algeria",
    "AD" to "Andorra",
    "AO" to "Angola",
    "AG" to "Antigua and Barbuda",
    "AR" to "Argentina",
    "AM" to "Armenia",
    "AU" to "Australia",
    "AT" to "Austria",
    "AZ" to "Azerbaijan",
    "BH" to "Bahrain",
    "BD" to "Bangladesh",
    "BB" to "Barbados",
    "BY" to "Belarus",
    "BE" to "Belgium",
    "BJ" to "Benin",
    "BT" to "Bhutan",
    "BO" to "Bolivia",
    "BA" to "Bosnia and Herzegovina",
    "BR" to "Brazil",
    "BN" to "Brunei",
    "BG" to "Bulgaria",
    "BF" to "Burkina Faso",
    "KH" to "Cambodia",
    "CM" to "Cameroon",
    "CA" to "Canada",
    "CF" to "Central African Republic",
    "TD" to "Chad",
    "CL" to "Chile",
    "CN" to "China",
    "CO" to "Colombia",
    "CR" to "Costa Rica",
    "CI" to "Cote d'Ivoire",
    "HR" to "Croatia",
    "CU" to "Cuba",
    "CY" to "Cyprus",
    "DK" to "Denmark",
    "DJ" to "Djibouti",
    "DO" to "Dominican Republic",
    "EC" to "Ecuador",
    "EG" to "Egypt",
    "SV" to "El Salvador",
    "GQ" to "Equatorial Guinea",
    "ER" to "Eritrea",
    "EE" to "Estonia",
    "ET" to "Ethiopia",
    "FJ" to "Fiji",
    "FI" to "Finland",
    "FR" to "France",
    "GA" to "Gabon",
    "GE" to "Georgia",
    "DE" to "Germany",
    "GH" to "Ghana",
    "GR" to "Greece",
    "GT" to "Guatemala",
    "GN" to "Guinea",
    "GY" to "Guyana",
    "HT" to "Haiti",
    "HN" to "Honduras",
    "HU" to "Hungary",
    "IS" to "Iceland",
    "IN" to "India",
    "ID" to "Indonesia",
    "IR" to "Iran",
    "IQ" to "Iraq",
    "IE" to "Ireland",
    "IL" to "Israel",
    "IT" to "Italy",
    "JM" to "Jamaica",
    "JP" to "Japan",
    "JO" to "Jordan",
    "KZ" to "Kazakhstan",
    "KE" to "Kenya",
    "KR" to "Korea, South",
    "KW" to "Kuwait",
    "KG" to "Kyrgyzstan",
    "LV" to "Latvia",
    "LB" to "Lebanon",
    "LR" to "Liberia",
    "LI" to "Liechtenstein",
    "LT" to "Lithuania",
    "LU" to "Luxembourg",
    "MG" to "Madagascar",
    "MY" to "Malaysia",
    "MV" to "Maldives",
    "MT" to "Malta",
    "MR" to "Mauritania",
    "MU" to "Mauritius",
    "MX" to "Mexico",
    "MD" to "Moldova",
    "MC" to "Monaco",
    "MN" to "Mongolia",
    "ME" to "Montenegro",
    "MA" to "Morocco",
    "NA" to "Namibia",
    "NP" to "Nepal",
    "NL" to "Netherlands",
    "NZ" to "New Zealand",
    "NI" to "Nicaragua",
    "NE" to "Niger",
    "NG" to "Nigeria",
    "MK" to "North Macedonia",
    "NO" to "Norway",
    "OM" to "Oman",
    "PK" to "Pakistan",
    "PA" to "Panama",
    "PG" to "Papua New Guinea",
    "PY" to "Paraguay",
    "PE" to "Peru",
    "PH" to "Philippines",
    "PL" to "Poland",
    "PT" to "Portugal",
    "QA" to "Qatar",
    "RO" to "Romania",
    "RU" to "Russia",
    "RW" to "Rwanda",
    "LC" to "Saint Lucia",
    "VC" to "Saint Vincent and the Grenadines",
    "SM" to "San Marino",
    "SA" to "Saudi Arabia",
    "SN" to "Senegal",
    "RS" to "Serbia",
    "SC" to "Seychelles",
    "SG" to "Singapore",
    "SK" to "Slovakia",
    "SI" to "Slovenia",
    "SO" to "Somalia",
    "ZA" to "South Africa",
    "ES" to "Spain",
    "LK" to "Sri Lanka",
    "SD" to "Sudan",
    "SR" to "Suriname",
    "SE" to "Sweden",
    "CH" to "Switzerland",
    "TZ" to "Tanzania",
    "TH" to "Thailand",
    "TG" to "Togo",
    "TT" to "Trinidad and Tobago",
    "TN" to "Tunisia",
    "TR" to "Turkey",
    "UG" to "Uganda",
    "UA" to "Ukraine",
    "AE" to "United Arab Emirates",
    "GB" to "United Kingdom",
    "UY" to "Uruguay",
    "US" to "US",
    "UZ" to "Uzbekistan",
    "VE" to "Venezuela",
    "VN" to "Vietnam",
    "ZM" to "Zambia",
    "ZW" to "Zimbabwe",
    "DM" to "Dominica",
    "GD" to "Grenada",
    "MZ" to "Mozambique",
    "SY" to "Syria",
    "TL" to "Timor-Leste",
    "BZ" to "Belize",
    "LA" to "Laos",
    "LY" to "Libya",
    "GW" to "Guinea-Bissau",
    "ML" to "Mali",
    "KN" to "Saint Kitts and Nevis",
    "BW" to "Botswana",
    "BI" to "Burundi",
    "SL" to "Sierra Leone",
    "MW" to "Malawi",
    "SS" to "South Sudan",
    "EH" to "Western Sahara",
    "ST" to "Sao Tome and Principe",
    "YE" to "Yemen",
    "KM" to "Comoros",
    "TJ" to "Tajikistan",
    "LS" to "Lesotho"
)